
### Blogs
GET http://localhost:3003/api/blogs
Content-Type: application/json
###
POST http://localhost:3003/api/blogs
Content-Type:application/json

{
    "title":"Hello World",
    "author":"Elias",
    "url":"",
    "likes":1,
    "userId":"606d97545eb08549d0baa8c2"
}
### Users
GET http://localhost:3003/api/users
Content-Type: application/json
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "elipet",
    "name": "Elias Peteri",
    "password": "salainen"
}
